### ISSUE TITLE
undefined: strings.ReplaceAll error during install

### ISSUE THREAD

**Issue by paulkaefer** [ynqa/diffy#2]
I get the following when running the `go get` instructions from the README:
```bash
Mon May 11 09:29:33
ubuntu ~ λ go get -u github.com/ynqa/diffy
# github.com/ynqa/diffy/pkg/diffy
go/src/github.com/ynqa/diffy/pkg/diffy/diffy.go:26:9: undefined: strings.ReplaceAll
```
I had to install go on the machine I use this on... is there some dependency that I also have to install?

**Comment by ynqa** [comment]
@paulkaefer What go version do you use? `ReplaceAll` function may be added on 1.12; https://golang.org/doc/go1.12#strings

**Comment by paulkaefer** [comment]
Updating fixed it. Thanks, @ynqa!
